### ISSUE TITLE
Proposal: make operations in @exclude an enum

### ISSUE THREAD

**Issue by Andy2003** [neo4j/graphql-tracker-temp#13]
I would suggest to make the values of the `operations` argument an enum. This makes it clearer to the user what values are available.

So for `*` an enum value of `ALL` could be used.

So the directive declaration would be:

```graphql
directive @exclude(operation:[ExcludeOptions!]! = [ALL]) on OBJECT
enum ExcludeOptions{
  CREATE,
  READ,
  UPDATE,
  DELETE
  ALL
}
```
setting the default value to `ALL` would allow to use the exclude directive without argument, so one can use it like:

```graphql
type Actor @exclude {
  name: String
}
```

**Comment by darrellwarde** [comment]
I'll be quite honest and put my hands up for not being too familiar with directive declarations. 😳  However, this could be used to address a lot of instances where we use strings to represent what should be enums throughout a lot of our directives. This is very cool.

**Comment by darrellwarde** [comment]
Raising a ticket in our inbox for this and #15.

**Comment by darrellwarde** [comment]
This now done and merged, ready for the next release. We've taken a slightly different tact of:

```
directive @exclude(operation:[ExcludeOptions!]) on OBJECT
enum ExcludeOptions{
  CREATE,
  READ,
  UPDATE,
  DELETE
}
```

Meaning users don't have "ALL" as a choice, and we manually set to all if the directive is used with an argument. But the intention is very much the same, and this behaviour is described in the description!

**Comment by Andy2003** [comment]
so the definition should be:

```graphql
directive @exclude(operation:[ExcludeOptions!] = [CREATE, READ, UPDATE, DELETE]) on OBJECT
enum ExcludeOptions{
  CREATE,
  READ,
  UPDATE,
  DELETE
}
```
