### ISSUE TITLE
Proposal: Make created or modified timestamps explicit

### ISSUE THREAD

**Issue by Andy2003** [neo4j/graphql-tracker-temp#16]
In the java world (JPA) we have annotations -which are directives in graphql - [for auditing data](https://springbootdev.com/2018/03/13/spring-data-jpa-auditing-with-createdby-createddate-lastmodifiedby-and-lastmodifieddate/)

Instead of using one annotation to cover all usecases like: `@autogenerate(operations: ["create"])` I would suggest to use different directives like:

- `@CreatedDate`
- `@LastModifiedDate`

In future also:

- `@CreatedBy`
- `@LastModifiedBy`

**Comment by danstarns** [comment]
Where do you see each directive mentioned being applied? On the type definition? Or a field?

**Comment by Andy2003** [comment]
on the field

**Comment by Andy2003** [comment]
```graphql
type Movie {
    id: ID
    createdAt: DateTime! @CreatedDate
    updatedAt: DateTime! @LastModifiedDate
}
```

**Comment by danstarns** [comment]
Not a bad idea, although I wouldn't say it's any more explicit than the current way of doing it. What if you wanted `upserted`... then you have to apply two directives? 

```graphql
type Movie {
    id: ID
    upsertedAt: DateTime! @CreatedDate @LastModifiedDate
}
```

**Comment by Andy2003** [comment]
> then you have to apply two directives?

Yes, this looks very familiar to me as a Java user :-)

**Comment by darrellwarde** [comment]
> Not a bad idea, although I wouldn't say it's any more explicit than the current way of doing it. What if you wanted `upserted`... then you have to apply two directives?
> 
> ```graphql
> type Movie {
>     id: ID
>     upsertedAt: DateTime! @CreatedDate @LastModifiedDate
> }
> ```

Personally not a fan of this at all, in my opinion would have to come up with a cleaner way of implementing this.

**Comment by danstarns** [comment]
One could argue just make a `@Upserted` directive and jobs a gooden. I think we need to consider the size and surface area of the library, if we introduce lots and lots of directives for each use case; how will that be to document & remember? Plus adding more directives restricts users in implementing there own.

**Comment by Andy2003** [comment]
> Personally not a fan of this at all, in my opinion would have to come up with a cleaner way of implementing this.

So if you stay with `@autogenerate`, you should at least make the `operations` argument an enum array.

**Comment by Andy2003** [comment]
> I think we need to consider the size and surface area of the library, if we introduce lots and lots of directives for each use case; how will that be to document & remember?

You can define a partial schema containing all the frameworks types (like e.g. `DeleteInfo`) and directives, add it to your npm  package the IDE will allow code completion and documentation for your types:

![image](https://user-images.githubusercontent.com/4464522/110155163-85296f00-7de5-11eb-8e0b-921ee0d957b8.png)

```graphql
"""
some nice doc
"""
directive @CreatedDate on FIELD_DEFINITION
```

Additionally you can define where the user can place the directive.

> Plus adding more directives restricts users in implementing there own.

come on...
but you can prefix all directives with `neo4j`

**Comment by darrellwarde** [comment]
> > I think we need to consider the size and surface area of the library, if we introduce lots and lots of directives for each use case; how will that be to document & remember?
> 
> You can define a partial schema containing all the frameworks types (like e.g. `DeleteInfo`) and directives, add it to your npm package the IDE will allow code completion and documentation for your types:
> 
> ![image](https://user-images.githubusercontent.com/4464522/110155163-85296f00-7de5-11eb-8e0b-921ee0d957b8.png)
> 
> ```graphql
> """
> some nice doc
> """
> directive @CreatedDate on FIELD_DEFINITION
> ```
> 
> Additionally you can define where the user can place the directive.

Love this, code completion for our directives would be a game changer.

**Comment by Andy2003** [comment]
This is the reason, why I extracted the directives and made them "static". So the Intellij graphql plugin will scan the whole project for `*.graphql` files and provides you with code completion.

![image](https://user-images.githubusercontent.com/4464522/110156350-206f1400-7de7-11eb-8df1-9f483bd1eeef.png)

**Comment by Andy2003** [comment]
![image](https://user-images.githubusercontent.com/4464522/110157274-46e17f00-7de8-11eb-8f59-5fba1b8a3130.png)
![image](https://user-images.githubusercontent.com/4464522/110157325-52cd4100-7de8-11eb-965f-6dbd4dc740b9.png)

**Comment by darrellwarde** [comment]
Yep, completely onboard with this, definitely going on the roadmap!

Time for me to relax for the evening. 😪  Thanks for all of the feedback on this, it's really valuable. Have a good weekend!

**Comment by darrellwarde** [comment]
Just for your information @Andy2003, with this we're taking the direction:

```graphql
directive @timestamp(operation: TimestampEvent! = UPSERT) on FIELD_DEFINITION
enum ExcludeOptions{
  CREATE,
  UPDATE,
  UPSERT
}
```

That would mean if someone wanted a general timestamp of the last update or creation, they just use @timestamp. And then if someone wanted two separate create and update fields, they would have @timestamp(operation: CREATE) and @timestamp(operation: UPDATE).

**Comment by darrellwarde** [comment]
This has now been implemented and will be in the next release. In the end, the definition is as follows:

```
enum TimestampOperation {
    CREATE
    UPDATE
}

"""Instructs @neo4j/graphql to generate timestamps on particular events, which will be available as the value of the specified field."""
directive @timestamp(
    """Which events to generate timestamps on. Defaults to both create and update."""
    operations: [TimestampOperation!]! = [CREATE, UPDATE]
) on FIELD_DEFINITION
```
