### ISSUE TITLE
Contributors

### ISSUE THREAD

**Issue by dlcognite** [neo4j/graphql-tracker-temp#8]
Hi, I would love to help contribute and support this library.

I had some working proposals to add additional features to the GRAND stack like bulk (which seems solved here) and aggregation (https://github.com/cognitedata/neo4j-graphql-js/pull/5). 

I would love to help make the graphql integration even better 🤩

**Comment by darrellwarde** [comment]
Hi @dlcognite, thank you for the message of supported, and we're really excited to already see people wanting to contribute to this library!

This project is absolutely going to be made open source, at the very latest when we release version 1.0.0 (which is currently scheduled for April/May time), and we would love to accept contributions at this point! However, at the moment, we are very much in "move fast and break things" mode as we work towards feature completeness by that point. We are also only two people working on this, and community pull requests at this time might be the straw that breaks the camels back so to speak!

Once we are at 1.0.0, things are going to be a lot more stable and we're going to have more time available for these kind of activities.

Aggregations are, however, on our roadmap, so we'd love to hear how you would like to see them implemented. I encourage you to raise a feature request issue in this repo explaining what your thoughts are in terms of how they would fit into the schema.

In the meantime, closing this issue as accepting contributions is indeed on our roadmap in the near future. Thanks!
